### PR TITLE
Implement Refresh Token Flow

### PR DESCRIPTION
**Pull request by jeffreyflynt**
This implements the refresh token flow.

I see the refresh token is stored along with the access token, so I modified `getRefreshToken` to query on the Access Token collection.

Let me know if you have any questions or suggestions.

### CODE REVIEW

**Comment by jankapunkt** [comment]
Awesome @jeffreyflynt I will review after the weekend. @bratelefant this might be interesting to you, too

**Comment by jeffreyflynt** [comment]
It looks as if there were some linting issues, I fixed those and pushed another commit.

**Comment by jankapunkt** [comment]
@jeffreyflynt I'll need a bit more time because I need to complete Meteor 3.0 migration with this package

**Comment by jankapunkt** [comment]
@jeffreyflynt yes I already did that but didn't publish or push as I wanted to test locally first. I now made it public via #21 and also released ` leaonline:oauth2-server@6.0.0-rc.0`.

You can review it if you like. In the meantime I will check on your PR what I can do to get the tests fixed.

**Comment by jankapunkt** [comment]
@jeffreyflynt I would merge this into the current branch and release another Meteor 2.x compatible version with your contribution. For the #21 there needs to be a Meteor 3 compatible implementation. If you want I can add this to #21 but I'm also fine if you want to do it

**Review by jankapunkt — APPROVED** [review]

**Comment by MaxwelSant** [comment]
Hey @jeffreyflynt, how are you?
I wonder why we added the id field on retrieving client, but then change was rolled back: https://github.com/leaonline/oauth2-server/pull/19/commits/4526117991277747af498cf127e67b61b6f37bf6#diff-e58997fdbe2b8e4535e2dde27b344afe6f1bbf2aabecfbfdfd10727167a883a6R57
I ask because I'm having an issue on this exact point as `node-oauth2-server` tries to validate clientIds using field `client.id` but it is not matching as on client collection is saved as `clientId`.

**Comment by jankapunkt** [comment]
Hi @MaxwelSant @jeffreyflynt  the `clientDoc.id` is actually `clientDoc.clientId` but since you could theoretically save any other data, including an abitrary `id` value, it would get overridden by the former code.

However maybe I was thinking too strong in terms of abstraction and noone will ever come into that usecase?

**Pull request merged**
